# Generated by Django 5.1.5 on 2025-02-12 18:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecolution', '0003_remove_task_completed_usertask_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='usertask',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='task',
            name='points_given',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='task',
            name='predefined',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usertask',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='usertask',
            unique_together={('user', 'task', 'date_time')},
        ),
        migrations.CreateModel(
            name='EventTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecolution.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'event', 'date_time')},
            },
        ),
    ]
