# Generated by Django 5.1.5 on 2025-02-13 10:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecolution', '0005_rename_eventtask_userevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertask',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
