# Generated by Django 5.1.5 on 2025-02-13 15:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecolution', '0005_rename_eventtask_userevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertask',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterUniqueTogether(
            name='usertask',
            unique_together={('user', 'task', 'date')},
        ),
        migrations.AddField(
            model_name='pet',
            name='pet_exp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pet',
            name='pet_level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddConstraint(
            model_name='pet',
            constraint=models.CheckConstraint(condition=models.Q(('pet_exp__gte', 0), ('pet_exp__lte', 10)), name='pet_exp_range'),
        ),
        migrations.RemoveField(
            model_name='usertask',
            name='date_time',
        ),
    ]
