# Generated by Django 5.1.5 on 2025-02-17 12:48

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecolution', '0006_alter_usertask_unique_together_pet_pet_exp_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='pet',
            name='pet_exp_range',
        ),
        migrations.RemoveField(
            model_name='task',
            name='predefined',
        ),
        migrations.AddField(
            model_name='customuser',
            name='preferred_font_size',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='pet',
            name='pet_type',
            field=models.CharField(default='mushroom', max_length=50),
        ),
        migrations.AddField(
            model_name='pet',
            name='size',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='small', max_length=10),
        ),
        migrations.AddField(
            model_name='task',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='event',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Ecolution.event'),
        ),
        migrations.AddField(
            model_name='task',
            name='xp_given',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='pet',
            name='pet_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.CheckConstraint(condition=models.Q(('preferred_font_size__gte', 1), ('preferred_font_size__lte', 10)), name='pet_level_range'),
        ),
        migrations.AddConstraint(
            model_name='pet',
            constraint=models.CheckConstraint(condition=models.Q(('pet_exp__gte', 0), ('pet_exp__lte', django.db.models.expressions.CombinedExpression(models.Value(100), '+', django.db.models.expressions.CombinedExpression(models.F('pet_level'), '*', models.Value(20))))), name='pet_exp_range'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(fields=('task_name', 'creator'), name='unique_task_for_creator'),
        ),
    ]
