# Generated by Django 5.1.5 on 2025-02-13 10:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecolution', '0006_alter_usertask_date_time'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usertask',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='usertask',
            name='due_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterUniqueTogether(
            name='usertask',
            unique_together={('user', 'task', 'due_date')},
        ),
    ]
