# Generated by Django 5.1.5 on 2025-02-13 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecolution', '0007_alter_usertask_unique_together_usertask_due_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertask',
            old_name='due_date',
            new_name='date',
        ),
        migrations.AlterUniqueTogether(
            name='usertask',
            unique_together={('user', 'task', 'date')},
        ),
        migrations.AddField(
            model_name='pet',
            name='pet_exp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pet',
            name='pet_level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='task',
            name='xp_given',
            field=models.IntegerField(default=100),
        ),
        migrations.AddConstraint(
            model_name='pet',
            constraint=models.CheckConstraint(condition=models.Q(('my_number__gte', 0), ('my_number__lte', 10)), name='my_number_range'),
        ),
        migrations.RemoveField(
            model_name='usertask',
            name='date_time',
        ),
    ]
