# Generated by Django 5.1.5 on 2025-02-13 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecolution', '0008_rename_due_date_usertask_date_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pet',
            name='my_number_range',
        ),
        migrations.AddConstraint(
            model_name='pet',
            constraint=models.CheckConstraint(condition=models.Q(('pet_exp__gte', 0), ('pet_exp__lte', 10)), name='pet_exp_range'),
        ),
    ]
