# Generated by Django 5.1.5 on 2025-02-23 16:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecolution', '0008_event_date_event_location_event_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='userevent',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterUniqueTogether(
            name='userevent',
            unique_together={('user', 'event', 'date')},
        ),
        migrations.RemoveField(
            model_name='userevent',
            name='date_time',
        ),
    ]
