# Generated by Django 5.1.5 on 2025-02-23 16:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecolution', '0008_event_date_event_location_event_time'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='customuser',
            name='pet_level_range',
        ),
        migrations.AddField(
            model_name='userevent',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterUniqueTogether(
            name='userevent',
            unique_together={('user', 'event', 'date')},
        ),
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.CheckConstraint(condition=models.Q(('preferred_font_size__gte', 1), ('preferred_font_size__lte', 30)), name='preferred_font_size_range'),
        ),
        migrations.AddConstraint(
            model_name='pet',
            constraint=models.CheckConstraint(condition=models.Q(('pet_level__gte', 1), ('pet_level__lte', 10)), name='pet_level_range'),
        ),
        migrations.RemoveField(
            model_name='userevent',
            name='date_time',
        ),
    ]
