# Generated by Django 5.1.5 on 2025-02-13 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecolution', '0009_remove_pet_my_number_range_pet_pet_exp_range'),
    ]

    operations = [
    ]
