# Generated by Django 5.1.5 on 2025-02-24 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecolution', '0010_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='pet_level',
            field=models.IntegerField(default=1),
        ),
    ]
