# Generated by Django 5.1.5 on 2025-03-09 23:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecolution', '0012_remove_pet_pet_exp_range_pet_pet_exp_range'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=5000)),
            ],
        ),
        migrations.CreateModel(
            name='UserItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='pet',
            name='pet_level_range',
        ),
        migrations.AddField(
            model_name='customuser',
            name='displayed_pet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='displayed_for', to='Ecolution.pet'),
        ),
        migrations.AddField(
            model_name='useritem',
            name='shopitem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecolution.shopitem'),
        ),
        migrations.AddField(
            model_name='useritem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='useritem',
            unique_together={('user', 'shopitem')},
        ),
    ]
