# Generated by Django 5.1.5 on 2025-03-10 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecolution', '0013_shopitem_useritem_remove_pet_pet_level_range_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopitem',
            name='image_path',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='pet',
            name='pet_type',
            field=models.CharField(choices=[('mushroom', 'Mushroom'), ('acorn', 'Acorn'), ('plant', 'Plant')], default='mushroom', max_length=10),
        ),
    ]
