# Generated by Django 5.1.5 on 2025-03-12 13:38

from django.db import migrations
import uuid

def gen_uuid(apps, schema_editor):
    MyModel = apps.get_model("Ecolution", "event")
    for row in MyModel.objects.all():
        row.unique_token = uuid.uuid4()
        row.save(update_fields=["unique_token"])


class Migration(migrations.Migration):

    dependencies = [
        ('Ecolution', '0015_event_qr_code_event_unique_token_event_url_qr_code_and_more'),
    ]

    operations = [
        # omit reverse_code=... if you don't want the migration to be reversible.
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
