# Generated by Django 5.1.5 on 2025-03-12 13:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Ecolution', '0016_populate_uuid_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="unique_token",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
