# Generated by Django 5.1.5 on 2025-03-12 13:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecolution', '0017_remove_uuid_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='unique_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
