# Generated by Django 5.1.5 on 2025-03-22 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecolution', '0020_pet_hat_shopitem_is_hat_alter_task_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_gamekeeper',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='predefined',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='event',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Ecolution.event'),
        ),
        migrations.DeleteModel(
            name='GameKeeper',
        ),
    ]
